version: "3"
services:
  backend:
    image: node:8.15.0
    build: ./backend
    working_dir: /usr/src/app
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/usr/src/app:z
    depends_on:
      - mysql
    environment:
      - ENVIRONMENT=development
    command: ["npm", "start"]
   mysql:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=estacionamento
      - TZ=America/Sao_Paulo
volumes:
  database:
